### ISSUE TITLE
Issue with ppa:rmescandon

### ISSUE THREAD

**Issue by f-j-h** [bigbluebutton/bbb-install#246]
Hi there,

I tried to install BBB on my server today, but I just get this error ;-(

> Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 122, in <module>
    shortcut = shortcut_handler(line)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 864, in shortcut_handler
    ret = factory(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 407, in shortcut_handler
    return PPAShortcutHandler(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 364, in __init__
    info = get_ppa_info(self.shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 347, in get_ppa_info
    _get_suggested_ppa_message(user, ppa))
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 304, in _get_suggested_ppa_message
    lp_user = get_info_from_lp(LAUNCHPAD_USER_API % user)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 88, in get_info_from_lp
    return _get_https_content_py3(lp_url)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 110, in _get_https_content_py3
    lp_page = urllib.request.urlopen(request, cafile=LAUNCHPAD_PPA_CERT)
  File "/usr/lib/python3.5/urllib/request.py", line 153, in urlopen
    capath=capath)
  File "/usr/lib/python3.5/ssl.py", line 470, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
ssl.SSLError: unknown error (_ssl.c:3057)
+ apt-key list CC86BB64
+ grep -q -E '1024|4096'
+ err 'Unable to setup PPA for ppa:rmescandon/yq'
+ say 'Unable to setup PPA for ppa:rmescandon/yq'
+ echo 'bbb-install: Unable to setup PPA for ppa:rmescandon/yq'
bbb-install: Unable to setup PPA for ppa:rmescandon/yq
+ exit 1

**Comment by f-j-h** [comment]
Ok, got it solved :-)
I run these two commands:

> apt-get` --reinstall install ca-certificates

> dpkg-reconfigure ca-certificates

**Comment by ffdixon** [comment]
Thanks for sharing how you solved the issue.
