### ISSUE TITLE
new password generator function breaks greenlight

### ISSUE THREAD

**Issue by RokkuCode** [bigbluebutton/bbb-install#393]
the new password function introduced with #381 breaks greenlight from connection to postgresql due to special chars like / +
the function can generate such password:
```
cYe/43x8hIM5jwRbu/a+jl8P0gs5sUNo
```
this password does not work with greenlight and postgresql:
```
greenlight-v2 | FATAL: password authentication failed for user "postgres" Couldn't create 'greenlight_production' database. Please check your configuration. rake aborted! PG::ConnectionBad: FATAL: password authentication failed for user "postgres" /usr/src/app/vendor/bundle/ruby/2.7.0/gems/pg-0.21.0/lib/pg.rb:56:in `initialize' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/pg-0.21.0/lib/pg.rb:56:in `new' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/pg-0.21.0/lib/pg.rb:56:in `connect' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:118:in `retrieve_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:90:in `connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:119:in `create' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:313:in `each' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:138:in `create_current' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <main>' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>' /usr/local/bin/bundle:23:in `load' /usr/local/bin/bundle:23:in `<main>' Tasks: TOP => db:create (See full trace by running task with --trace)
```
if i remove the special chards everything is working again

**Comment by ffdixon** [comment]
Thanks for reporting this.  Fixed in https://github.com/bigbluebutton/bbb-install/commit/09d06a5c779b2dd1552bcac3aba22bf55dfffe78.
