### ISSUE TITLE
Errors: Installation BBB / Java / bbb-demo does not work

### ISSUE THREAD

**Issue by relecand** [bigbluebutton/bbb-install#429]
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-23 -s bbb01.xxxx.de -e xxxx@xxxx.de

bbb-install.sh version Sep 13, 2021: 

![grafik](https://user-images.githubusercontent.com/5286499/133242405-61d7ece0-6b43-422b-8eca-e44c441cc412.png)

Error 1:
```
Vormals nicht ausgewähltes Paket ibm-java80-jre:amd64 wird gewählt.
Vorbereitung zum Entpacken von .../005-ibm-java80-jre_8.0.6.5-0ubuntu1_amd64.deb ...

Licence Agreement license could not be presented
try 'dpkg-reconfigure debconf' to select a frontend other than noninteractive

dpkg: Fehler beim Bearbeiten des Archivs /tmp/apt-dpkg-install-soX1OW/005-ibm-java80-jre_8.0.6.5-0ubuntu1_amd64.deb (--unpack):
 »neues ibm-java80-jre:amd64-Skript des Paketes pre-installation«-Unterprozess gab den Fehlerwert 1 zurück
```

```
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 bbb-apps-akka : Depends: java8-runtime-headless
 bbb-fsesl-akka : Depends: java8-runtime-headless
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

With ```apt --fix-broken install``` I can continue the installation. 

```
The following additional packages will be installed:
  ibm-java80-jre
Suggested packages:
  ibm-java80-plugin
The following NEW packages will be installed:
  ibm-java80-jre
```

It prompts the LA screen:

![grafik](https://user-images.githubusercontent.com/5286499/133237128-c1ca9a9e-3cc6-42be-8392-f0496887a7f9.png)

Then:

Error 2:
```
Successfully installed rubygems-update-3.2.27
Installing RubyGems 3.2.27
Traceback (most recent call last):
	3: from setup.rb:22:in `<main>'
	2: from setup.rb:22:in `require'
	1: from /var/lib/gems/2.5.0/gems/rubygems-update-3.2.27/lib/rubygems.rb:1328:in `<top (required)>'
/var/lib/gems/2.5.0/gems/rubygems-update-3.2.27/lib/rubygems.rb:1341:in `rescue in <top (required)>': uninitialized constant Gem::BasicSpecification (NameError)
Loading the rubygems/defaults/operating_system.rb file caused an error. This file is owned by your OS, not by rubygems upstream. Please find out which OS package this file belongs to and follow the guidelines from your OS to report the problem and ask for help.
```

But the installation continues.

Then again:

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-23 -s bbb01.xxxx.de -e xxxx@xxxx.de

----
Then I tried to install the api-demos:

```apt install bbb-demo```

Error 3:
```
See "systemctl status tomcat8.service" and "journalctl -xe" for details.
invoke-rc.d: initscript tomcat8, action "start" failed.
● tomcat8.service - LSB: Start Tomcat.
   Loaded: loaded (/etc/init.d/tomcat8; generated)
   Active: failed (Result: exit-code) since Tue 2021-09-14 12:00:52 CEST; 5ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 18272 ExecStart=/etc/init.d/tomcat8 start (code=exited, status=1/FAILURE)

Sep 14 12:00:52 bbb01 systemd[1]: Starting LSB: Start Tomcat....
Sep 14 12:00:52 bbb01 tomcat8[18272]:  no JDK or JRE found - please set JAVA_HOME
Sep 14 12:00:52 bbb01 systemd[1]: tomcat8.service: Control process exited, code=exited status=1
Sep 14 12:00:52 bbb01 systemd[1]: tomcat8.service: Failed with result 'exit-code'.
Sep 14 12:00:52 bbb01 systemd[1]: Failed to start LSB: Start Tomcat..
dpkg: error processing package tomcat8 (--configure):
 installed tomcat8 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-demo:
 bbb-demo depends on tomcat8; however:
  Package tomcat8 is not configured yet.
```
ll /usr/lib/jvm/

```
lrwxrwxrwx  1 root root   18 Feb 10  2020 ibm-java80-jre-x86_64 -> java-ibm-x86_64-80/
-rw-r--r--  1 root root  457 Feb 10  2020 .ibm-java80-jre-x86_64.jinfo
drwxr-xr-x  3 root root 4096 Jun  7  2016 java-9-openjdk-amd64/
drwxr-xr-x  5 root root 4096 Sep 14 11:57 java-ibm-x86_64-80/
```

I checked out this version of the bbb-install script: https://github.com/bigbluebutton/bbb-install/tree/80eb637b814878ad1af29c59fa988ac45cca7456 (version of Sep 8, 2021). The errors 1 and 2 did not appear. I think there are bugs within the commits of Sep 13, 2021.

**Comment by relecand** [comment]
Edit: 

```apt-get install openjdk-8-jdk```helped to install the bbb-demo

**Comment by michi-80337** [comment]
This issue could be a side effect of the first part from commit d8898edc32bcfe476fdb617da1efd84a5fcbead9. I will set up a new VM and try to reproduce this problem in the next days. If someone else is faster: Don't be shy, ...

**Comment by michi-80337** [comment]
As promised, I did the test installation today. I installed a plain fresh Ubuntu:

    root@test-bbb:~# cat /etc/os-release
    [...]
    VERSION="18.04.6 LTS (Bionic Beaver)"
    [...]

I got the error messages from "Error 2", too. It seems to be a [well known issue](https://github.com/rubygems/rubygems/issues/4186) for the RubyGems people.

Nevertheless the installation succeeded, and I installed the bbb-demo. First I got a "502 Bad gateway" error from nginx when I tried to join a conference. Everything was fine after doing a `bbb-conf --restart`. I neither had to manually accept any licenses nor to install some packages before I start.

What I might have done differently:

- After the base installation from Ubuntu I did an `apt-get update; apt-get upgrade` and restarted the server.
- I seperated the `wget` fetch and script execution to be able to check the source code in case of any problems.

**Comment by relecand** [comment]
Thank you very much. I did also tests with two other servers. But I was not able to reproduce the bugs on the other servers (only error 2).

**Comment by relecand** [comment]
I have been able to reproduce the error. I've got a fresh Ubuntu 18.04 installation, but with wrong package lists in /etc/apt/sources.list

I updated /etc/apt/sources.list to

```

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://de.archive.ubuntu.com/ubuntu bionic main restricted
# deb-src http://de.archive.ubuntu.com/ubuntu bionic main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://de.archive.ubuntu.com/ubuntu bionic-updates main restricted
# deb-src http://de.archive.ubuntu.com/ubuntu bionic-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://de.archive.ubuntu.com/ubuntu bionic universe
# deb-src http://de.archive.ubuntu.com/ubuntu bionic universe
deb http://de.archive.ubuntu.com/ubuntu bionic-updates universe
# deb-src http://de.archive.ubuntu.com/ubuntu bionic-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://de.archive.ubuntu.com/ubuntu bionic multiverse
# deb-src http://de.archive.ubuntu.com/ubuntu bionic multiverse
deb http://de.archive.ubuntu.com/ubuntu bionic-updates multiverse
# deb-src http://de.archive.ubuntu.com/ubuntu bionic-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://de.archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
# deb-src http://de.archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu bionic partner
# deb-src http://archive.canonical.com/ubuntu bionic partner

deb http://de.archive.ubuntu.com/ubuntu bionic-security main restricted
# deb-src http://de.archive.ubuntu.com/ubuntu bionic-security main restricted
deb http://de.archive.ubuntu.com/ubuntu bionic-security universe
# deb-src http://de.archive.ubuntu.com/ubuntu bionic-security universe
deb http://de.archive.ubuntu.com/ubuntu bionic-security multiverse
```

... and then it worked.

**Comment by relecand** [comment]
Would it be possible to check the /etc/apt/sources.list in the install-script?

**Comment by BaseMax** [comment]
same problem in Ubuntu 18.04.

```
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -a -v bionic-23 -s s1.**** -e info@****
```

**Comment by ffdixon** [comment]
Can you try the install again -- just pushed an [update](https://github.com/bigbluebutton/bbb-install/commit/2cf126606abe5a4b2295e1f833ac31ddcbe93767) to ensure that Java 1.8 is installed on Bionic.

**Comment by BaseMax** [comment]
Thank you for the update, Fred.
I will test the script again on a fresh Ubuntu 18.04 and let you know. 👌

**Comment by BaseMax** [comment]
Dear Fred,

I tested the new script on fresh Ubuntu and it installed automatically without harm.

Thank you so much for your help and for fixing the bug.
You saved my day. @ffdixon 

So by the way, we can close this ISSUE.

Regards,
