### ISSUE TITLE
Mediasoup installation fails in 2.4-rc3

### ISSUE THREAD

**Issue by worldthumbler** [bigbluebutton/bbb-install#451]
**Describe the bug**
Installation of mediasoup fails when using bbb-install 

**To Reproduce**

Make a BBB-installation with `-v bionic-240-2.4-rc-3` on a blank server

**Expected behavior**
mediasoup can be used with minor changes [see wiki](https://github.com/bigbluebutton/bbb-webrtc-sfu/wiki/Back-of-the-envelope-calculations:-mediasoup#using-mediasoup-in-a-24--rc2-installation)

**Actual behavior**
Error during the installation and missing of the directory `/etc/bigbluebutton/bbb-webrtc-sfu/` 
Mediasoup must be installed manually, see [development installation routine](https://github.com/bigbluebutton/bbb-webrtc-sfu/wiki/Back-of-the-envelope-calculations:-mediasoup#using-mediasoup-in-a-development-environment)

**Log from bbb-install**
<pre>&gt; bufferutil@4.0.3 install /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/bufferutil
&gt; node-gyp-build

&gt; ws@0.4.32 install /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws
&gt; (node-gyp rebuild 2&gt; builderror.log) || (exit 0)

make: Entering directory &apos;/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/build&apos;
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:113: recipe for target &apos;Release/obj.target/bufferutil/src/bufferutil.o&apos; failed
make: Leaving directory &apos;/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/build&apos;

&gt; mediasoup@3.8.4 postinstall /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mediasoup
&gt; node npm-scripts.js postinstall

npm-scripts.js [INFO] running task &quot;postinstall&quot;
npm-scripts.js [INFO] executing command: make -C worker
make: Entering directory &apos;/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mediasoup/worker&apos;
/usr/bin/python2 ./scripts/configure.py -R mediasoup-worker
Error: you need to install gyp in deps/gyp first, run:
  ./scripts/get-dep.sh gyp
Makefile:24: recipe for target &apos;default&apos; failed
make: *** [default] Error 42
make: Leaving directory &apos;/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mediasoup/worker&apos;
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ELIFECYCLE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> mediasoup@3.8.4 postinstall: `node npm-scripts.js postinstall`
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Exit status 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Failed at the mediasoup@3.8.4 postinstall script.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /root/.npm/_logs/2021-10-27T09_05_35_719Z-debug.log
</pre>

last rows from ` /root/.npm/_logs/2021-10-27T08_44_16_508Z-debug.log`
<pre>***
520 info lifecycle mediasoup@3.8.4~preinstall: mediasoup@3.8.4
521 info linkStuff mediasoup@3.8.4
522 silly linkStuff mediasoup@3.8.4 has /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules as its parent node_modules
523 verbose rebuildBundles [ &apos;.bin&apos;, &apos;uuid&apos; ]
524 info lifecycle mediasoup@3.8.4~install: mediasoup@3.8.4
525 info lifecycle mediasoup@3.8.4~postinstall: mediasoup@3.8.4
526 verbose lifecycle mediasoup@3.8.4~postinstall: unsafe-perm in lifecycle true
527 verbose lifecycle mediasoup@3.8.4~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mediasoup/node_modules/.bin:/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
528 verbose lifecycle mediasoup@3.8.4~postinstall: CWD: /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mediasoup
529 silly lifecycle mediasoup@3.8.4~postinstall: Args: [ &apos;-c&apos;, &apos;node npm-scripts.js postinstall&apos; ]
530 silly lifecycle mediasoup@3.8.4~postinstall: Returned: code: 1  signal: null
531 info lifecycle mediasoup@3.8.4~postinstall: Failed to exec postinstall script
532 verbose stack Error: mediasoup@3.8.4 postinstall: `node npm-scripts.js postinstall`
532 verbose stack Exit status 1
532 verbose stack     at EventEmitter.&lt;anonymous&gt; (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
532 verbose stack     at EventEmitter.emit (events.js:314:20)
532 verbose stack     at ChildProcess.&lt;anonymous&gt; (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
532 verbose stack     at ChildProcess.emit (events.js:314:20)
532 verbose stack     at maybeClose (internal/child_process.js:1022:16)
532 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
533 verbose pkgid mediasoup@3.8.4
534 verbose cwd /usr/local/bigbluebutton/bbb-webrtc-sfu
535 verbose Linux 4.15.0-161-generic
536 verbose argv &quot;/usr/bin/node&quot; &quot;/usr/bin/npm&quot; &quot;rebuild&quot;
537 verbose node v12.22.7
538 verbose npm  v6.14.15
539 error code ELIFECYCLE
540 error errno 1
541 error mediasoup@3.8.4 postinstall: `node npm-scripts.js postinstall`
541 error Exit status 1
542 error Failed at the mediasoup@3.8.4 postinstall script.
542 error This is probably not a problem with npm. There is likely additional logging output above.
543 verbose exit [ 1, true ]
</pre>

trivia:
bbb-webrtc-sfu v2.6.0-beta.5
bbb bionic-240-2.4-rc-3
reproducable: yes

**Comment by worldthumbler** [comment]
Closed by Release 2.4-rc4
