### ISSUE TITLE
very old certbot from repository, suggest switch to snapd version

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bbb-install#721]
certbot got error: 
**Unable to register an account with ACME serve**r
log:
```
2024-02-02 08:19:12,078:DEBUG:certbot._internal.main:certbot version: 1.21.0
2024-02-02 08:19:12,078:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2024-02-02 08:19:12,078:DEBUG:certbot._internal.main:Arguments: ['--email', 'info@opd.com-c', '--agree-tos', '--rsa-key-size', '4096', '-w', '/var/www/bigbluebutton-default/assets/', '-d', 'opencnd.com', '--deploy-hook', 'systemctl reload nginx', '--webroot', '--non-interactive']
2024-02-02 08:19:12,078:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-02-02 08:19:12,090:DEBUG:certbot._internal.log:Root logging level set at 30
2024-02-02 08:19:12,092:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-02-02 08:19:12,092:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f8d634e3e80>
Prep: True
2024-02-02 08:19:12,092:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f8d634e3e80> and installer None
2024-02-02 08:19:12,092:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-02-02 08:19:14,915:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-02-02 08:19:14,918:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-02-02 08:19:15,109:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2024-02-02 08:19:15,109:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 02 Feb 2024 08:19:15 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "_ABeZUWfCt8": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-02/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-02-02 08:19:15,110:DEBUG:acme.client:Requesting fresh nonce
2024-02-02 08:19:15,110:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-02-02 08:19:15,161:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-02-02 08:19:15,162:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 02 Feb 2024 08:19:15 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 5IXlosaqyluolfaNqq0Vm6W3s61OuL-m9t1luxPt5Ezf-HpoDMc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-02-02 08:19:15,162:DEBUG:acme.client:Storing nonce: 5IXlosaqyluolfaNqq0Vm6W3s61OuL-m9t1luxPt5Ezf-HpoDMc
2024-02-02 08:19:15,162:DEBUG:acme.client:JWS payload:
b'{\n  "contact": [\n    "mailto:info@openca.com-c"\n  ],\n  "termsOfServiceAgreed": true\n}'
2024-02-02 08:19:15,174:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-acct:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAiandrIjogeyJuIjogInlzb0w1MnBwVEJmMWtwTENsVkZjcFFIN2MxZVpFU04tZnZfQWotVWRiTlBESEtoQzIxVWd6djUwajRORzR1Rzk1RjVJVWRQMFVvUXNGMUg5SUlIb2FsVkhIVmRsUlQtZnZDcjNvcW1xczMyaWNiVWxYbTdBcGFGMHkyU0otLUlPdUthNlVseEllSlEwUGxQTXM4V0pfLTlEN1pNRk5kdUxEUkNFQ3dCVUlBR3hnemZ5OEp5YncxTnZZQkhtS0tLMUY4eFdBLVBSdjJHako1M2gwdEUzY2xib1RabGlzZmpnV2ZzNHMzb1RPdDJFbTc4Y3g1WTFaQnBCNzlrdUd4aERaOHhNNXdFVGQxV3RPcmx3bmtUbGNaVDNCaXBVTHpxWWtUbVJHWU1hN3BJamtkYl9GX1UwTDA5SDMyQXNBb25aSHRNUm5nanptZWx1TGR0NXdfNWZJMkNzVE9qcW1feHFhSjlSMWIyRnlCQS1JaWV4VjF3LUhpYllQcHZVc1p4UmYzSnZCM3gydWV3TjFOeGZvaFhpaFk3YktpYzZ2OUNHdUwyTE1MOGctLTEydHBRMUdsR1J1RW5hejE0T0xKQ1Q5NEtzaXR1S2Z6UVVXaEg2MmFLWmNidFoxOTVrODRIeWtDckRBQkR5NVptR2x0SFN4dklfeXBISTBWSFlKZlVyWkJwUFFSUGhWLVc3Y1ZqX1dmczkwVmNYWkZlcnJrS2lGQkY4WUg3STZMNVNtWTQ5VFNMaFlCSWZybkMteFcyVFlFVHRDQzF5aTNrQmU3ZVMwZkpheDFocWc1SWdsbm1PZGhhVjJBTW12d0dRaEZHZXk5MjhORGdnblJ4REU3cjNFampPd0gzYm9iNV9PNVU1VTNYZXRGOHRXNWlZelA2ako1STQ0TVhSNGlFIiwgImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIn0sICJub25jZSI6ICI1SVhsb3NhcXlsdW9sZmFOcXEwVm02VzNzNjFPdUwtbTl0MWx1eFB0NUV6Zi1IcG9ETWMiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1hY2N0In0",
  "signature": "RGDCf8uoDCw3kEg_WJa5MnoeBKYuK0-cAbghEkiK3LAkXAzLe2VBuTqv87vaRWzZIuN29EyRVJBX9Efu_XR0vMy9J7Ew49qFAnePSiYMTkP4UPSsGattTTZuaLM0xI1uwe-IIwkZhL1kHt1lblYqaUvgFTPxhMVNe72cwLaElSyw86eSmlilaHXZLtsfSnmmzGiMQRgshw1u9HVTBSTW_GUmsAGhCTvT4zLCWzSYSoaGhMKwAXJ6tp0OJeoCwEh84GGEjcXencqcrR3SpXlDrrRI6JoK77geF_V72V0VxHEo03aBbGTFVEUfuk9A5fSw1w98XxN6d2iGDewgYvsgQQIVnoQEJcUm3bYNA2r9tT8GyS2D7m5J73HNdjmO3FpVnZB0D1I3BtN0-Jo1St811szSotP9nrHZrL757wwnXDYqe8NvDwqHvKNG6xLACJ_v598IGEzgHXxl3keu_gYrjCNcyJRffcT2Vr8ImXeC-1zhRzfWvM-pnmiRphMEZAbArOAlAT1FKkF-77UESCOSydv4NsnO0y7cIvE3arM7_Y8r_BPfxRw5RlB5Va90lsvudznW5gZkO4aKVD0CTF3bN4PDA40FN9Zw8QOZraJOexvRlIj7LnQk5rwBDzeNqH8srXg7Uje4Nge94JZy7lnjODYuqiLgNvxUm_G4OaPawEI",
  "payload": "ewogICJjb250YWN0IjogWwogICAgIm1haWx0bzppbmZvQG9wZW5jYXN0Lm5peG1pbmQuY29tLWMiCiAgXSwKICAidGVybXNPZlNlcnZpY2VBZ3JlZWQiOiB0cnVlCn0"
}
2024-02-02 08:19:15,286:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-acct HTTP/1.1" 400 244
2024-02-02 08:19:15,287:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Date: Fri, 02 Feb 2024 08:19:15 GMT
Content-Type: application/problem+json
Content-Length: 244
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 3l89SrA752gGHWc_BGWStJwSj1eGjcTvsJWoWv2ZrjbgRy-xwn4

{
  "type": "urn:ietf:params:acme:error:invalidContact",
  "detail": "Error creating new account :: contact email \"info@openind.com-c\" has invalid domain : Domain name does not end with a valid public suffix (TLD)",
  "status": 400
}
2024-02-02 08:19:15,287:DEBUG:certbot._internal.main:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 229, in perform_registration
    return acme.new_account_and_tos(newreg, tos_cb)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 910, in new_account_and_tos
    return client_v2.new_account(regr)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 630, in new_account
    response = self._post(self.directory['newAccount'], new_account)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 101, in _post
    return self.net.post(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1269, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1283, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1128, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:invalidContact :: The provided contact URI was invalid :: Error creating new account :: contact email "info@opemind.com-c" has invalid domain : Domain name does not end with a valid public suffix (TLD)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 680, in _determine_account
    acc, acme = client.register(
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 186, in register
    regr = perform_registration(acme, config, tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 236, in perform_registration
    raise errors.Error(msg)
certbot.errors.Error: The ACME server believes info@opend.com-c is an invalid email address. Please ensure it is a valid email and attempt registration again.
2024-02-02 08:19:15,289:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 229, in perform_registration
    return acme.new_account_and_tos(newreg, tos_cb)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 910, in new_account_and_tos
    return client_v2.new_account(regr)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 630, in new_account
    response = self._post(self.directory['newAccount'], new_account)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 101, in _post
    return self.net.post(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1269, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1283, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1128, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:invalidContact :: The provided contact URI was invalid :: Error creating new account :: contact email "info@opencast.nixmind.com-c" has invalid domain : Domain name does not end with a valid public suffix (TLD)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 680, in _determine_account
    acc, acme = client.register(
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 186, in register
    regr = perform_registration(acme, config, tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 236, in perform_registration
    raise errors.Error(msg)
certbot.errors.Error: The ACME server believes info@open.com-c is an invalid email address. Please ensure it is a valid email and attempt registration again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==1.21.0', 'console_scripts', 'certbot')())
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1574, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1416, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 763, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 687, in _determine_account
    raise errors.Error(
certbot.errors.Error: Unable to register an account with ACME server

```

version compare form apt repository and snap
```
root@open:~# apt list -a certbot
Listing... Done
certbot/jammy,now 1.21.0-1build1 all [installed]

root@opencast:~# snap install --classic certbot
certbot 2.8.0 from Certbot Project (certbot-eff✓) installed
```

**Comment by amg-web** [comment]
acme.sh is a good alternative
