### ISSUE TITLE
error ip does not match if config / domain.com

### ISSUE THREAD

**Issue by edgard-arch** [bigbluebutton/bbb-install#95]
ip does not match ifconfig / domain.com

is there a way to correct this error to redirect to SSL, when I write domain.com redirects me to http and not to https

Cheers

**Comment by ffdixon** [comment]
The title is 'Potential Problems' so consider this a warning message than an error.  For example, on our demo server we get

~~~

# Potential problems described below
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 66.70.179.61
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: demo.bigbluebutton.org

~~~

But it still works.  Consider the above more of a warning (not an error).

For redirection of http to https, you can rewrite the top of your `/etc/nginx/sites-available/bigbluebutton` as follows (here were using `demo.bigbluebutton.org` but substitute your domain name).

Change

~~~
server {
  listen 80;
  listen [::]:80;

  listen 443 ssl;
  listen [::]:443 ssl;
  server_name demo.bigbluebutton.org;
...
~~~

To
~~~
server {
  listen 80;
  listen [::]:80;
  server_name demo.bigbluebutton.org;

  return 302 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name demo.bigbluebutton.org;
...
~~~

This will take incoming connections to port 80 and redirect them to HTTPS.  Try the above and let us

**Comment by edgard-arch** [comment]
hello, redirect! thanks !
Now I should be able to make a video call but my problem is that it takes me to https://sub.domain.com/demo/demoHTML5: 404 Not Found

Do I have to install the API demo ??? or the next step you would have to do is install greenlight

**Comment by ffdixon** [comment]
You'll need to use some front-end.  The API demos are really just demos (not meant for production and `sudo bbb-conf --check` will warn you that they are installed and need to be removed.

Definitely recommend using [Greenlight](https://github.com/bigbluebutton/greenlight) as a front-end if are not planning on using any of the [others](https://bigbluebutton.org/integrations/).

**Comment by edgard-arch** [comment]
Hi Fred, thanks! I am reading the greenlight installation documentation but cannot create the .env file by running the following command
docker run --rm bigbluebutton / greenlight: v2 cat ./sample.env> .env
I'm going to try creating it manually and copying the codes from github.

there is a forum where you find some similar installation issues greetings
regards

**Comment by ffdixon** [comment]
Can you try running

~~~
docker run --rm bigbluebutton/greenlight:v2 cat ./docker-compose.yml > ~/greenlight/docker-compose.yml
~~~

This is the command we're using to automate the setup of Greenlight using [bbb-install.sh](https://github.com/bigbluebutton/bbb-install/).

**Comment by edgard-arch** [comment]
Hi Fred, I tell you:
make the configuration of the .env file manually and verify the file with the command, the following appears to me:
root@vmi339006:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
rake aborted!
ArgumentError: `secret_key_base` for production environment must be a type of String`
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:583:in `validate_secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:432:in `secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:176:in `key_generator'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:205:in `message_verifier'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activestorage-5.2.3/lib/active_storage/engine.rb:81:in `block (2 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/usr/src/app/config/environment.rb:23:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => conf:check => environment
(See full trace by running task with --trace)

I also executed the command you sent me ...... docker-compose.yml and created the .yml file and followed the steps on using composer.
Then configure Nginx to route to Greenlight and it can also be the default page.
takes me to the page pointing out 404 Not Found

What do you think he's doing wrong :( :( 
regards

**Comment by farhatahmad** [comment]
Hi @edgard-arch,
> secret_key_base for production environment must be a type of String

Did you edit the `.env` file and add in the secret key that you generated?

**Comment by edgard-arch** [comment]
hello, if you actually place Edit the .env file and add the secret key that generated the commands sudo bbb-conf --secret and sudo bbb-conf --secret.
I don't think it has anything to do with copying sample.env from https://github.com/greelight and modifying the file and editing from it.

I just checked the settings and it appears

root@vmi339006:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
rake aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:585:in `validate_secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:432:in `secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:176:in `key_generator'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:205:in `message_verifier'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activestorage-5.2.3/lib/active_storage/engine.rb:81:in `block (2 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/usr/src/app/config/environment.rb:23:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => conf:check => environment
(See full trace by running task with --trace)
root@vmi339006:~/greenlight# ^C
root@vmi339006:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
rake aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:585:in `validate_secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:432:in `secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:176:in `key_generator'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:205:in `message_verifier'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activestorage-5.2.3/lib/active_storage/engine.rb:81:in `block (2 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/usr/src/app/config/environment.rb:23:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => conf:check => environment
(See full trace by running task with --trace)

From what I see it is about the environment variable configuration, checking I can't find the relative root / b, where should I find it? , any suggestions or reinstalling with bbb-install.sh could solve my problem with greenlight
Keep investigating
regards!

**Comment by edgard-arch** [comment]
Still unsolved, any suggestions from someone? please or better reinstall with the command bbb-install.sh? 
regards

**Comment by farhatahmad** [comment]
Hi @edgard-arch,

> ArgumentError: Missing secret_key_base for 'production' environment

The `SECRET_KEY_BASE` variable in the `.env` file is not set, which is what is causing this error

**Comment by kiruam** [comment]
I am currently trying to configure a server
bigbluebutton, the server is hosted in a VDC (Virtual Data Center), both the Firewall and the NAT are the ports required by the documentation, the installation is executed with the following command: wget -qO- https: // ubuntu .bigbluebutton.org / bbb-install.sh | bash -s - -v xenial-22 and once it has finished everything has been correct with the ip 172.30.5.20 which corresponds to the internal network, I use the following command sudo bbb-conf --setip classesbbb.kpdataeditores.com for the update to BigBlueButton configuration files to use hostname, once this configuration finishes and I run the command sudo bbb-conf --check I get the following error.

**# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 172.30.5.20
#   /etc/nginx/sites-available/bigbluebutton: clasesbbb.kpdataeditores.com
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    http://clasesbbb.kpdataeditores.com/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Error: Unable to connect to port 1935 (RTMP) on clasesbbb.kpdataeditores.com

# Error: Unable to reach default URL for presentation:
#
#    http://clasesbbb.kpdataeditores.com/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties**

I am testing the connection from the moodle front-end and I get the following error.

**Unable to join the session. Please check the URL of the BigBlueButton server and check that the BigBlueButton server is running.**

When I perform the tests on the internal network, I can enter the application, it marks a microphone and video error, so I am trying to assign a domain to be able to generate the SSL security certificates.

**Comment by sebaxyz** [comment]
Hi Team,

I am having the same problem from moodle, can not connect message. 
The installation configured the private ip in the services and my first attempt to correct this was to configure the public ip but nothing yet.

When I ran bbb-conf --check I received the potential error message about the ip matching.

Thanks in advance for your help
Sebastian.

**Comment by sebaxyz** [comment]
To improve the information about this issue I am pasting some commands outputs:
bbb-conf --version

ii  bbb-apps                              1:2.0.0-52                                    amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.0.0-155                                     all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.0.0-41                                    amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.0.0-15                                    amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.0.0-29                                    amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.0.0-8                                     amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.0.0-407                                   amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.0.0-89                                    amd64        BigBlueButton configuration utilities
ii  bbb-freeswitch-core                   2:2.0.0-50                                    amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-9                                     amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.0.0-27                                      all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.0.0-486                                   amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-4                                     amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.0.0-31                                    amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.0.0-37                                    amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.8-40                                    amd64        The Red5 server for BigBlueButton
ii  bbb-swftools                          1:0.9.2-2                                     amd64        The swftools files for BigBlueButton
ii  bbb-transcode-akka                    2.0.0-6                                       all          BigBlueButton Transcoder
ii  bbb-web                               1:2.0.0-95                                    amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.0.0-88                                    amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.0.0-13                                    amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                     amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library for image scaling and various conversions - runtime files

bbb-conf --status
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server.service ——► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]

sudo bbb-conf --check

BigBlueButton Server 2.0.0 (1694)
                    Kernel version: 4.15.0-1089-azure
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16403 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbbserver.<fqdn>
                              red5: bbbserver.<fqdn>
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                         websocket: :7443
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbbserver.<fqdn>
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: bbbserver.<fqdn>

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: bbbserver.<fqdn>
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento)
                        kurentoUrl: ws://10.0.0.5:8888/kurento
                         kurentoIp: 10.0.0.5
                    localIpAddress: 10.0.0.5
               recordScreenSharing: true
                     recordWebcams: true
                              Node: v8.17.0
                           mongoDB: v3.4.24


** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: 10.0.0.5
#   /etc/nginx/sites-available/bigbluebutton: bbbserver.<fqdn>

# Warning: The setting of PUBLIC IP for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.0.0.5).
# (This is OK if you've manually changed the values)

**Comment by onahoz** [comment]
> To improve the information about this issue I am pasting some commands outputs:
> 
> # bbb-conf --version
> ```
> ii  bbb-apps                              1:2.0.0-52                                    amd64        BigBlueButton applications for Red5
> ii  bbb-apps-akka                         2.0.0-155                                     all          BigBlueButton Apps (Akka)
> ii  bbb-apps-screenshare                  1:2.0.0-41                                    amd64        BigBlueButton screenshare module for Red5
> ii  bbb-apps-sip                          1:2.0.0-15                                    amd64        BigBlueButton SIP module for Red5
> ii  bbb-apps-video                        1:2.0.0-29                                    amd64        BigBlueButton video module for Red5
> ii  bbb-apps-video-broadcast              1:2.0.0-8                                     amd64        BigBlueButton video broadcast module for Red5
> ii  bbb-client                            1:2.0.0-407                                   amd64        BigBlueButton Flash client
> ii  bbb-config                            1:2.0.0-89                                    amd64        BigBlueButton configuration utilities
> ii  bbb-freeswitch-core                   2:2.0.0-50                                    amd64        BigBlueButton build of FreeSWITCH
> ii  bbb-freeswitch-sounds                 1:1.6.7-9                                     amd64        FreeSWITCH Sounds
> ii  bbb-fsesl-akka                        2.0.0-27                                      all          BigBlueButton FS-ESL (Akka)
> ii  bbb-html5                             1:2.0.0-486                                   amd64        The HTML5 components for BigBlueButton
> ii  bbb-mkclean                           1:0.8.7-4                                     amd64        Clean and optimize Matroska and WebM files
> ii  bbb-playback-presentation             1:2.0.0-31                                    amd64        BigBluebutton playback of presentation
> ii  bbb-record-core                       1:2.0.0-37                                    amd64        BigBlueButton record and playback
> ii  bbb-red5                              1:1.0.8-40                                    amd64        The Red5 server for BigBlueButton
> ii  bbb-swftools                          1:0.9.2-2                                     amd64        The swftools files for BigBlueButton
> ii  bbb-transcode-akka                    2.0.0-6                                       all          BigBlueButton Transcoder
> ii  bbb-web                               1:2.0.0-95                                    amd64        BigBlueButton API
> ii  bbb-webrtc-sfu                        1:2.0.0-88                                    amd64        BigBlueButton WebRTC SFU
> ii  bigbluebutton                         1:2.0.0-13                                    amd64        Open source web conferencing platform (bbb)
> ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                     amd64        Tools for transcoding, streaming and playing of multimedia files
> ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
> ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library for handling input and output devices - runtime files
> ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library containing media filters - runtime files
> ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
> ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg compatibility library for resampling - runtime files
> ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library with functions for simplifying programming - runtime files
> ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library for post processing - runtime files
> ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
> ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                     amd64        FFmpeg library for image scaling and various conversions - runtime files
> ```
> 
> # bbb-conf --status
> ```
> red5 ——————————————————► [✔ - active]
> tomcat7 ———————————————► [✔ - active]
> nginx —————————————————► [✔ - active]
> freeswitch ————————————► [✔ - active]
> redis-server.service ——► [✔ - active]
> bbb-apps-akka —————————► [✔ - active]
> bbb-transcode-akka ————► [✔ - active]
> bbb-fsesl-akka ————————► [✔ - active]
> mongod ————————————————► [✔ - active]
> bbb-html5 —————————————► [✔ - active]
> bbb-webrtc-sfu ————————► [✔ - active]
> kurento-media-server ——► [✔ - active]
> ```
> 
> # sudo bbb-conf --check
> ```
> BigBlueButton Server 2.0.0 (1694)
>                     Kernel version: 4.15.0-1089-azure
>                       Distribution: Ubuntu 16.04.6 LTS (64-bit)
>                             Memory: 16403 MB
> 
> /var/www/bigbluebutton/client/conf/config.xml (bbb-client)
>                 Port test (tunnel): rtmp://bbbserver.<fqdn>
>                               red5: bbbserver.<fqdn>
>               useWebrtcIfAvailable: true
> 
> /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
>                          websocket: :7443
>                     WebRTC enabled: true
> 
> /etc/nginx/sites-available/bigbluebutton (nginx)
>                        server name: bbbserver.<fqdn>
>                               port: 80, [::]:80
>                     bbb-client dir: /var/www/bigbluebutton
> 
> /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
>                       bbb-web host: bbbserver.<fqdn>
> 
> /usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
>                   voice conference: FreeSWITCH
> 
> /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
>                      playback host: bbbserver.<fqdn>
>                             ffmpeg: 4.2.2-1bbb1~ubuntu16.04
> 
> /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento)
>                         kurentoUrl: ws://10.0.0.5:8888/kurento
>                          kurentoIp: 10.0.0.5
>                     localIpAddress: 10.0.0.5
>                recordScreenSharing: true
>                      recordWebcams: true
>                               Node: v8.17.0
>                            mongoDB: v3.4.24
> 
> 
> * Potential problems described below
>  IP does not match:
>                            IP from ifconfig: 10.0.0.5
>    /etc/nginx/sites-available/bigbluebutton: bbbserver.<fqdn>
> 
>  Warning: The setting of PUBLIC IP for proxy_pass in
> 
>     /etc/bigbluebutton/nginx/sip.nginx
> 
>  does not match the local IP address (10.0.0.5).
>  (This is OK if you've manually changed the values)
> ```

Hi i am having the same problem. Did you find a solution? 
Thank you.

**Comment by Davka** [comment]
Try apt-get install host

**Comment by onahoz** [comment]
> Try apt-get install host

thanks for reply, it does not help I still get

# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 10.10.13.201
#   /etc/nginx/sites-available/bigbluebutton: sub.domain.com

# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 10.10.13.201
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: sub.domain.com

I am unable to join demo either
